sql: make casts from strings require Assignment context
Previously, all casts from string required Explicit CastContexts.
This was fine because literal string expressions were Explicitly
cast to their target types. However, implementing ScalarType::Char
has illustrated that the appropriate CastContext for literal
strings is Assignment.

Consider the following from Postgres 13:
```
sean=# create table n (a numeric);
CREATE TABLE
sean=# insert into n values ('1.23');
INSERT 0 1
```

This is by definition an Assignment context, and is valid.

```
sean=# create table c (a char(2));
CREATE TABLE
sean=# insert into c values ('123'::text);
ERROR:  value too long for type character(2)
```

This implies that on an Assignment cast, the length typmod is
checked.

```
sean=# select '123'::text::char(2);
 bpchar
--------
 12
```

However, on an Explicit cast, values are truncated.

This indicates that there are different behaviors for Assignment
and Explicit text to char casts, and that untyped string literals
use the Assignment context.